[mypy]
python_version = 3.13
files = src
ignore_missing_imports = True
warn_unused_configs = True
exclude = (?x)(
    ^\.git/
    | ^\.mypy_cache/
    | ^\.test/
    | ^\.trash/
    | ^\.venv/
    | ^__pycache__/
    | ^chromadb/
    | ^data/
    )
